test_that("install_pkg_cli_apps installs launchers for matching scripts", {
  pkg <- "rappTestBasic"
  fake <- setup_fake_rapp_package(tempdir(), "-install-basic", package = pkg)
  on.exit(unlink(fake[["lib"]], recursive = TRUE), add = TRUE)

  app_path <- file.path(fake[["exec"]], "hello.R")
  writeLines(
    c(
      "#!/usr/bin/env Rapp",
      "print('hello, world!')"
    ),
    app_path
  )

  # Should be ignored because first line lacks the keyword.
  writeLines(
    c(
      "not a launcher candidate",
      "print('skip me')"
    ),
    file.path(fake[["exec"]], "skip.R")
  )

  destdir <- tempfile("rapp-bin-basic")
  on.exit(unlink(destdir, recursive = TRUE), add = TRUE)

  expect_false(dir.exists(destdir))

  messages <- character()
  created <- withCallingHandlers(
    install_pkg_cli_apps(pkg, destdir = destdir, lib.loc = fake[["lib"]]),
    message = function(m) {
      messages <<- c(messages, conditionMessage(m))
      invokeRestart("muffleMessage")
    }
  )
  expect_true(any(grepl("^created:", messages)))

  expect_true(dir.exists(destdir))

  expected_launcher <- if (is_windows()) {
    file.path(destdir, "hello.bat")
  } else {
    file.path(destdir, "hello")
  }

  expect_equal(created, expected_launcher)
  expect_equal(list.files(destdir, full.names = TRUE), expected_launcher)

  lines <- readLines(expected_launcher)
  if (is_windows()) {
    expect_match(
      lines[[1]],
      sprintf(
        "^:: Generated by `Rapp::install_pkg_cli_apps\\(package = \"%s\"\\)`\\. Do not edit by hand\\.$",
        pkg
      )
    )
  } else {
    expect_identical(lines[[1]], "#!/bin/sh")
    expect_match(
      lines[[2]],
      sprintf(
        "^# Generated by `Rapp::install_pkg_cli_apps\\(package = \"%s\"\\)`\\. Do not edit by hand\\.$",
        pkg
      )
    )
  }
  expect_true(any(grepl("Rapp::run()", lines, fixed = TRUE)))
  expect_true(any(grepl("hello.R", lines, fixed = TRUE)))
})


test_that("front matter customises launcher options", {
  pkg <- "rappTestFront"
  fake <- setup_fake_rapp_package(
    tempdir(),
    "-install-frontmatter",
    package = pkg
  )
  on.exit(unlink(fake[["lib"]], recursive = TRUE), add = TRUE)

  app_path <- file.path(fake[["exec"]], "opts.R")
  writeLines(
    c(
      "#!/usr/bin/env -S Rscript -e 'Rapp::run()'",
      "#| launcher:",
      "#|   vanilla: true",
      "#|   'no-environ': true",
      "#|   'no-site-file': true",
      "#|   'no-init-file': true",
      "#|   restore: true",
      "#|   save: true",
      "#|   verbose: true",
      "#|   default_packages: [stats]",
      "print('options test')"
    ),
    app_path
  )

  destdir <- tempfile("rapp-bin-frontmatter")
  on.exit(unlink(destdir, recursive = TRUE), add = TRUE)

  messages <- character()
  created <- withCallingHandlers(
    install_pkg_cli_apps(pkg, destdir = destdir, lib.loc = fake[["lib"]]),
    message = function(m) {
      messages <<- c(messages, conditionMessage(m))
      invokeRestart("muffleMessage")
    }
  )
  expect_true(any(grepl("^created:", messages)))

  expected_launcher <- if (is_windows()) {
    file.path(destdir, "opts.bat")
  } else {
    file.path(destdir, "opts")
  }
  expect_equal(created, expected_launcher)

  lines <- readLines(expected_launcher)
  exec_line <- lines[length(lines)]
  expect_true(grepl("--vanilla", exec_line, fixed = TRUE))
  expect_true(grepl("--no-environ", exec_line, fixed = TRUE))
  expect_true(grepl("--no-site-file", exec_line, fixed = TRUE))
  expect_true(grepl("--no-init-file", exec_line, fixed = TRUE))
  expect_true(grepl("--restore", exec_line, fixed = TRUE))
  expect_true(grepl("--save", exec_line, fixed = TRUE))
  expect_true(grepl("--verbose", exec_line, fixed = TRUE))
  expect_true(grepl("--default-packages=stats", exec_line, fixed = TRUE))
  expect_false(grepl(paste0("base,", pkg), exec_line, fixed = TRUE))
  expect_true(grepl("Rapp::run()", exec_line, fixed = TRUE))
})


test_that("install_pkg_cli_apps prunes orphaned launchers", {
  pkg <- "rappTestPrune"
  fake <- setup_fake_rapp_package(tempdir(), "-install-prune", package = pkg)
  on.exit(unlink(fake[["lib"]], recursive = TRUE), add = TRUE)

  keep_path <- file.path(fake[["exec"]], "keep.R")
  drop_path <- file.path(fake[["exec"]], "drop.R")
  writeLines(c("#!/usr/bin/env Rapp", "print('keep')"), keep_path)
  writeLines(c("#!/usr/bin/env Rapp", "print('drop')"), drop_path)

  destdir <- tempfile("rapp-bin-prune")
  on.exit(unlink(destdir, recursive = TRUE), add = TRUE)

  messages <- character()
  first_created <- withCallingHandlers(
    install_pkg_cli_apps(pkg, destdir = destdir, lib.loc = fake[["lib"]]),
    message = function(m) {
      messages <<- c(messages, conditionMessage(m))
      invokeRestart("muffleMessage")
    }
  )
  expect_true(sum(grepl("^created:", messages)) == 2L)

  keep_launcher <- if (is_windows()) {
    file.path(destdir, "keep.bat")
  } else {
    file.path(destdir, "keep")
  }
  drop_launcher <- if (is_windows()) {
    file.path(destdir, "drop.bat")
  } else {
    file.path(destdir, "drop")
  }

  expect_setequal(first_created, c(keep_launcher, drop_launcher))
  expect_true(all(file.exists(c(keep_launcher, drop_launcher))))

  unlink(drop_path)

  messages <- character()
  second_created <- withCallingHandlers(
    install_pkg_cli_apps(pkg, destdir = destdir, lib.loc = fake[["lib"]]),
    message = function(m) {
      messages <<- c(messages, conditionMessage(m))
      invokeRestart("muffleMessage")
    }
  )

  expect_true(any(grepl("^created: ", messages)))
  expect_true(any(grepl(paste0("^deleted: ", drop_launcher), messages)))
  expect_equal(second_created, keep_launcher)
  expect_true(file.exists(keep_launcher))
  expect_false(file.exists(drop_launcher))
})
